config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :instruments, only: [:new, :edit, :create, :update, :destroy]
  resources :tempos, only: [:new, :edit, :create, :update, :destroy]
  resources :keys, only: [:new, :edit, :create, :update, :destroy]
  resources :eras, only: [:new, :edit, :create, :update, :destroy]
  resources :paces, only: [:new, :edit, :create, :update, :destroy]
  resources :moods, only: [:new, :edit, :create, :update, :destroy]
  resources :genres, only: [:new, :edit, :create, :update, :destroy]
  resources :artists
  resources :songs
  resources :projects
  get 'projects/add_song/:song_id' => 'projects#add_song', as: :add_song_project
  post 'projects/submit_song/:song_id' => 'projects#submit_song', as: :submit_song_project
  get 'edit_song_project/:id' => 'projects#edit_song', as: :edit_song_project
  delete 'projects/delete_song/:id' => 'projects#delete_song', as: :delete_song_project
  post 'projects/submit_project' => 'projects#submit_project', as: :submit_project
  resources :favorite_projects, only: [:create, :destroy, :playlist]
  resources :quotes do
    member do
      get :share
    end
  end
  resources :posts do
    resources :comments
  end
  resources :songs do
    member do
      get :download
      get :share
      get :add_to_cart
      post :add_to_cart
      post 'add_song'
      post 'remove_song'
      post :update_play_count
    end
  end
  resources :playlists do
    member do
      post 'add_song'
      post 'remove_song'
    end
  end
  resources :contacts, only: [:new, :create]

  resources :shopping_cart_items, only: [:destroy]
  
  get '/cart', to: 'shopping_cart_items#index'

  post '/checkout', to: 'shopping_cart_items#checkout'

  get '/purchases', to: 'purchase_items#index'
  get '/placements', to: 'purchase_items#placements'

  get '/purchased_items/:id/download', to: 'purchase_items#download', as: :download

  get '/home', to:  'pages#home'
  get '/credits', to: 'users#user_credits'
  get '/new_credit', to: 'users#new_credit'
  post '/submit_credit', to: 'users#submit_credit'

  get '/usermod', to:  'users#admin'

  get '/relationships', to:  'artists#relationships'
  post '/save_similar_artist/:id', to:  'artists#save_similar_artist', as: :save_similar_artist
  post '/artists/save_featured/:id', to: 'artists#save_featured'
  post '/artists/save_as_active/:id', to: 'artists#save_as_active'
  match "/submit_your_music" => "artists#new_artist_submission", as: :submit_your_music, via: [:get, :post]
  get '/about', to:  'pages#about'

  get '/contact', to: 'contacts#new'

  get '/film', to:  'pages#film'

  get '/horror', to:  'pages#horror'

  get '/games', to:  'pages#games'

  get '/ads', to:  'pages#ads'

  get '/video', to:  'pages#video'

  get '/blog', to:  'posts#index'

  get '/terms', to:  'pages#terms'

  get '/submit', to:  'artists#new_artist_submission'

  get '/faq', to:  'pages#faq'

  get '/play', to: 'songs#library'

  get '/favorites', to: 'songs#favorite'

  get '/dabooth', to: 'pages#admin'

  get '/teamzudosongadminpage', to: 'songs#admin'
  get '/teamzudosongapprovalpage', to: 'songs#approvals'
  post '/approve_deny_song/:id', to: 'songs#approve_deny', as: :approve_deny_song
  get '/denied-songs', to: 'songs#denied_songs', as: :denied_songs
  get '/deny_song/:id', to: 'songs#deny_song', as: :deny_song

  get '/sorry', to: 'pages#deny'

  get '/studio', to: 'songs#seller'

  get '/romance', to: 'pages#romance'



  as :user do
    get "/login" => "devise/sessions#new"
    get '/signup', to: 'registrations#new'
  end

  get '/share_zudo', to: 'site#share_zudo', as: :share_zudo

  get '/must_login', to: 'site#must_login', as: :must_login

  root 'pages#home'

  get '/genres', to: redirect('/play')
  get '/genres/:id', to: redirect('/play')
  get '/moods', to: redirect('/play')
  get '/moods/:id', to: redirect('/play')
  get '/paces', to: redirect('/play')
  get '/paces/:id', to: redirect('/play')
  get '/eras', to: redirect('/play')
  get '/eras/:id', to: redirect('/play')
  get '/keys', to: redirect('/play')
  get '/keys/:id', to: redirect('/play')
  get '/tempos', to: redirect('/play')
  get '/tempos/:id', to: redirect('/play')
  get '/instruments', to: redirect('/play')
  get '/instruments/:id', to: redirect('/play')

end

app/models/tempo.rb
class Tempo < ActiveRecord::Base
	default_scope { order(name: :asc) }
	has_many :songs
	
	validates :name, :desc, presence: true
end

app/controllers/tempos_controller.rb
class TemposController < ApplicationController
  before_action :set_tempo, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:index, :create, :show]
  # GET /tempos
  # GET /tempos.json
#  def index
#    @tempos = Tempo.all    
#  end

  # GET /tempos/1
  # GET /tempos/1.json
#  def show
#  end

  # GET /tempos/new
  def new
  end

  # GET /tempos/1/edit
  def edit
  end

  # POST /tempos
  # POST /tempos.json
  def create
    @tempo = Tempo.new(tempo_params)
    respond_to do |format|
      if @tempo.save
        format.html { redirect_to @tempo, notice: 'Tempo was successfully created.' }
        format.json { render :show, status: :created, location: @tempo }
      else
        format.html { render :new }
        format.json { render json: @tempo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tempos/1
  # PATCH/PUT /tempos/1.json
  def update
    respond_to do |format|
      if @tempo.update(tempo_params)
        format.html { redirect_to @tempo, notice: 'Tempo was successfully updated.' }
        format.json { render :show, status: :ok, location: @tempo }
      else
        format.html { render :edit }
        format.json { render json: @tempo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tempos/1
  # DELETE /tempos/1.json
  def destroy
    @tempo.destroy
    respond_to do |format|
      format.html { redirect_to tempos_url, notice: 'Tempo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tempo
      @tempo = Tempo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tempo_params
      params.require(:tempo).permit(:name, :desc)
    end
end

app/helpers/tempos_helper.rb
module TemposHelper
end

app/views/tempos/_form.html.erb
<%= form_for(@tempo) do |f| %>
  <% if @tempo.errors.any? %>
      <% @tempo.errors.full_messages.each do |message| %>
        <%= js add_gritter(message, :image => :warning ) %>
      <% end %>
  <% end %>
  <div class="field offWhite">
    <!--<%= f.label :name %><br>-->
    <%= f.text_field :name, :placeholder => 'Enter Tempo Name' %>
    <!--<%= f.label :desc %><br>-->
    <%= f.text_area :desc, :placeholder => 'Enter Tempo Description' %>
    <%= f.submit 'Save Tempo', :class => 'submitBTN' %>
  </div>
<% end %>

app/views/tempos/edit.html.erb
<% provide(:title, "EDIT TEMPO") %>
<div class="page-title">
	<div class="container">
		<h1>Edit Tempo</h1>
		<p>Please enter information for all sections of the form below to edit a tempo into the library.</p>
	</div>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Show', @tempo %> |
		<%= link_to 'Back', tempos_path %>
	</div>
</div>

app/views/tempos/index.html.erb
<% provide(:title, 'TEMPOS') %>
<% provide(:description, "Filter Songs by Tempo Category") %>
<% provide(:keywords, "Songs by Tempo") %>
<div class="page-title">
  <div class="container">
    <h1>Song Tempos</h1>
    <p>Filter our library by any of the song tempos below</p>
  </div>
</div>
<section class="section sect-pad">
  <div class="container">
    <% @tempos.each do |tempo| %>
      <%= link_to tempo_path(tempo) do %>
        <div class="optCard">
          <div class="optCard-image offWhite">
            <%= image_tag('tempo_image') %>
          </div>
          <div class="optCard-title center">
            <h2><%= tempo.name %></h2>
          </div>
          <div class="optCard-desc center">
            <%= tempo.desc %>
          </div>
          <div class="optCard-admin">
            <% if can? :manage, Tempo %>
              <%= link_to 'Show', tempo %> | 
              <%= link_to 'Edit', edit_tempo_path(tempo) %> | 
              <%= link_to 'Destroy', tempo, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <% if can? :manage, Tempo %>
      <div class="center">
        <%= link_to 'Add New Tempo', new_tempo_path, :class => 'btn btn-ghost' %>
      </div>
    <% end %>
  </div>
</section>

app/views/tempos/new.html.erb
<% provide(:title, "ADD TEMPO") %>
<div class="page-title">
	<div class="container">
		<h1>Add New Tempo</h1>
		<p>Please enter information for all sections of the form below to enter a new tempo into the library.</p>
	</div>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Back', tempos_path %>
	</div>
</div>

app/views/tempos/show.html.erb
<% provide(:title, @tempo.name) %>
<% provide(:description, @tempo.name + " Songs Available for Synch Licensing in Film and TV Soundtracks") %>
<% provide(:keywords, @tempo.name + " Songs") %>
<div class="page-title">
	<div class="container">
		<h1><%= @tempo.name %> Songs</h1>
    	<p><%= @tempo.desc %></p>
	</div>
</div>
<section class="catPlayerWrap">
	<table class="songlist">
	  <thead class="songlistHead">
	    <tr>
	      <th>Artwork</th>
	      <th>Title</th>
	      <th>Artist</th>
	      <th>Genre</th>
	      <th>Mood</th>
	      <th>Pace</th>
	      <th>Era</th>
	      <th>Key</th>
	      <th>Instrument</th>
	      <th> </th>
	    </tr>
	  </thead>
	  <tbody>
	    <% Song.where(tempo_id: @tempo.id).each do |song| %>
	      <tr class="songRow">
	        <td>
	          <div class="songRowPlay">
	            <a href="#">
	              <i class="ion-ios-play"></i>
	              <%= image_tag song.image.url, class: 'songRowArt' %>
	            </a>
	          </div>
	        </td>
	        <td><a href="#"><%= link_to song.title, song_path(song.id) %></a></td>
	        <td><%= link_to Artist.find(song.artist_id).name, artist_path(song.artist_id) %></td>
	        <td><%= link_to Genre.find(song.genre_id).name, genre_path(song.genre_id) %></td>
	        <td><%= link_to Mood.find(song.mood_id).name, mood_path(song.mood_id) %></td>
	        <td><%= link_to Pace.find(song.pace_id).name, pace_path(song.pace_id) %></td>
	        <td><%= link_to Era.find(song.era_id).name, era_path(song.era_id) %></td>
	        <td><%= link_to Key.find(song.key_id).name, key_path(song.key_id) %></td>
           <td><%= link_to Instrument.find(song.instrument_id).name, instrument_path(song.instrument_id) %></td>
	        <td class="storeBTNs">
	            <a href="#"><i class="ion-ios-star-outline"></i></a>
	            <a href="#"><i class="ion-ios-cloud-download-outline"></i></a> 
	            <a href="#"><i class="ion-ios-cart-outline"></i></a>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</section>