config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :instruments, only: [:new, :edit, :create, :update, :destroy]
  resources :tempos, only: [:new, :edit, :create, :update, :destroy]
  resources :keys, only: [:new, :edit, :create, :update, :destroy]
  resources :eras, only: [:new, :edit, :create, :update, :destroy]
  resources :paces, only: [:new, :edit, :create, :update, :destroy]
  resources :moods, only: [:new, :edit, :create, :update, :destroy]
  resources :genres, only: [:new, :edit, :create, :update, :destroy]
  resources :artists
  resources :songs
  resources :projects
  get 'projects/add_song/:song_id' => 'projects#add_song', as: :add_song_project
  post 'projects/submit_song/:song_id' => 'projects#submit_song', as: :submit_song_project
  get 'edit_song_project/:id' => 'projects#edit_song', as: :edit_song_project
  delete 'projects/delete_song/:id' => 'projects#delete_song', as: :delete_song_project
  post 'projects/submit_project' => 'projects#submit_project', as: :submit_project
  resources :favorite_projects, only: [:create, :destroy, :playlist]
  resources :quotes do
    member do
      get :share
    end
  end
  resources :posts do
    resources :comments
  end
  resources :songs do
    member do
      get :download
      get :share
      get :add_to_cart
      post :add_to_cart
      post 'add_song'
      post 'remove_song'
      post :update_play_count
    end
  end
  resources :playlists do
    member do
      post 'add_song'
      post 'remove_song'
    end
  end
  resources :contacts, only: [:new, :create]

  resources :shopping_cart_items, only: [:destroy]
  
  get '/cart', to: 'shopping_cart_items#index'

  post '/checkout', to: 'shopping_cart_items#checkout'

  get '/purchases', to: 'purchase_items#index'
  get '/placements', to: 'purchase_items#placements'

  get '/purchased_items/:id/download', to: 'purchase_items#download', as: :download

  get '/home', to:  'pages#home'
  get '/credits', to: 'users#user_credits'
  get '/new_credit', to: 'users#new_credit'
  post '/submit_credit', to: 'users#submit_credit'

  get '/usermod', to:  'users#admin'

  get '/relationships', to:  'artists#relationships'
  post '/save_similar_artist/:id', to:  'artists#save_similar_artist', as: :save_similar_artist
  post '/artists/save_featured/:id', to: 'artists#save_featured'
  post '/artists/save_as_active/:id', to: 'artists#save_as_active'
  match "/submit_your_music" => "artists#new_artist_submission", as: :submit_your_music, via: [:get, :post]
  get '/about', to:  'pages#about'

  get '/contact', to: 'contacts#new'

  get '/film', to:  'pages#film'

  get '/horror', to:  'pages#horror'

  get '/games', to:  'pages#games'

  get '/ads', to:  'pages#ads'

  get '/video', to:  'pages#video'

  get '/blog', to:  'posts#index'

  get '/terms', to:  'pages#terms'

  get '/submit', to:  'artists#new_artist_submission'

  get '/faq', to:  'pages#faq'

  get '/play', to: 'songs#library'

  get '/favorites', to: 'songs#favorite'

  get '/dabooth', to: 'pages#admin'

  get '/teamzudosongadminpage', to: 'songs#admin'
  get '/teamzudosongapprovalpage', to: 'songs#approvals'
  post '/approve_deny_song/:id', to: 'songs#approve_deny', as: :approve_deny_song
  get '/denied-songs', to: 'songs#denied_songs', as: :denied_songs
  get '/deny_song/:id', to: 'songs#deny_song', as: :deny_song

  get '/sorry', to: 'pages#deny'

  get '/studio', to: 'songs#seller'

  get '/romance', to: 'pages#romance'



  as :user do
    get "/login" => "devise/sessions#new"
    get '/signup', to: 'registrations#new'
  end

  get '/share_zudo', to: 'site#share_zudo', as: :share_zudo

  get '/must_login', to: 'site#must_login', as: :must_login

  root 'pages#home'

  get '/genres', to: redirect('/play')
  get '/genres/:id', to: redirect('/play')
  get '/moods', to: redirect('/play')
  get '/moods/:id', to: redirect('/play')
  get '/paces', to: redirect('/play')
  get '/paces/:id', to: redirect('/play')
  get '/eras', to: redirect('/play')
  get '/eras/:id', to: redirect('/play')
  get '/keys', to: redirect('/play')
  get '/keys/:id', to: redirect('/play')
  get '/tempos', to: redirect('/play')
  get '/tempos/:id', to: redirect('/play')
  get '/instruments', to: redirect('/play')
  get '/instruments/:id', to: redirect('/play')

end

app/models/project.rb
class Project < ActiveRecord::Base

	validates :name, presence: true
	validates :name, uniqueness: {scope: :user_id}

	belongs_to :user
	has_many :projects_songs

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  respond_to :html, :json
  before_action :authenticate_user!, except: [:show]
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :validate_user_project, only: [:edit, :update, :destroy]
  before_action :set_song, only: [:add_song, :submit_song]
  

  def index
    @projects = current_user.projects.order("created_at desc")
  end

  def show
    @songlist = ProjectsSong.where(project_id: @project.id).page(params[:page]).order("created_at desc")
  end

  # GET /paces/new
  def new
    return redirect_to projects_path, notice: "You can create only 5 projects." if current_user.projects.size >= 5
    @project = Project.new
  end

  # GET /paces/1/edit
  def edit
  end

  # POST /paces
  # POST /paces.json
  def create
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    return redirect_to projects_path, notice: "You can create only 5 projects." if current_user.projects.size >= 5
    if @project.save
      redirect_to projects_path, notice: 'Project was successfully created.' 
    else
      flash[:error] = 'Project was not created.' 
      render action: :new
    end
  end

  # PATCH/PUT /paces/1
  # PATCH/PUT /paces/1.json
  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: 'Project was successfully updated.' 
    else
      flash[:error] = 'Project was not updated.' 
      render action: :edit
    end
  end

  # DELETE /paces/1
  # DELETE /paces/1.json
  def destroy
    @project.destroy if @project.present?
    redirect_to projects_path, notice: 'Project was successfully destroyed.'   
  end

  def add_song
    respond_modal_with @song
  end

  def edit_song
    @project_song = ProjectsSong.find_by_id(params[:id])
    return redirect_to root_path, notice: "Wrong Access." if @project_song.blank? || (@project_song.user_id != current_user.id)
    @song = @project_song.song
    respond_modal_with @song
  end

  def delete_song
    project_song = ProjectsSong.find_by_id(params[:id])
    return redirect_to root_path, notice: "Wrong Access." if project_song.blank? || (project_song.user_id != current_user.id)
    redirect_to request.referer, notice: 'Song was successfully deleted from your project.' if project_song && project_song.destroy
  end

  def submit_song
    @errors  = {}
    @errors[:project] = "Project can't be blank" if params[:project_song][:project_id].blank?
    return render :submit_song if @errors.present?
    #@errors[:desc] = "Notes can't be blank" if params[:project_song][:desc].blank?
    #return render :submit_song if @errors.present?

    project_id = params[:project_song][:project_id]
    song_id = params[:song_id]
    project_name = Project.where(id: project_id).first.try(:name)
    
    project_song = ProjectsSong.where(user_id: current_user.id, project_id: project_id, song_id: song_id).first
    
    if project_song.blank?
      project_song = ProjectsSong.new(project_song_params) 
      project_song.song_id = @song.try(:id)
      project_song.user_id = current_user.id
      project_song.save
      @success = "Song successfully added in your Project #{project_name}."
    else
      project_song.update(project_song_params)
       @success = "Song successfully updated in your Project #{project_name}."
    end

  end

  def submit_project
    @errors  = {}
    @errors = "Project name can't be blank" if params[:project][:name].blank?
    return render :submit_project if @errors.present?
   
    @project = Project.new(project_params)
    @project.user_id = current_user.id

    @errors =  "You can create only 5 projects." if current_user.projects.size >= 5
    return render :submit_project if @errors.present?

    if @project.save

      @success = "Project was successfully created. Please select from the list."
      @projects = current_user.projects.order("created_at desc").pluck(:name, :id)
      
    else
      @errors = @project.errors.full_messages[0]
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find_by_id(params[:id])
      return redirect_to root_path, notice: "Project does not exists." if @project.blank?
    end

    def validate_user_project
      return redirect_to root_path, notice: "Wrong Access." if @project.user_id != current_user.id
    end

    def set_song
      @song = Song.find(params[:song_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :desc)
    end

    def project_song_params
      params.require(:project_song).permit(:project_id, :desc)
    end
end

app/views/projects/_form.html.slim
- set_meta_tags(site: 'Zudo', title: heading)

#contactPage
  .container
    h1.page-title 
    h2.page-sub-title =heading

    = simple_form_for(@project, html: {class: 'contact-form' }) do |f|
      - if @project.errors.any?
        - @project.errors.full_messages.each do |message|
          = js add_gritter(message, :image => :warning )
      = f.input :name, placeholder: "Project Name", label: false
      = f.input :desc, as: :text, :placeholder => "Project Description", input_html: {:rows => 5}, label: false
      button =btn_text


    
   

app/views/projects/_project_list.html.erb
<%= select_tag("project_song_project_id", options_for_select(@projects), prompt: "Select a Project") %>

app/views/projects/add_song.html.erb
<%= content_for :id, 'share-quote-modal' %>

<h1>Add This Song to Your Project</h1>

<% if current_user.projects.size < 5 %>
  <p><%= link_to "Create A New Project", "javascript:", id: "new_project_popup" %></p>
<% end %>

<div id="project-success" style="color:green;"></div>
<div class="field offWhite new-project" style="display:none;">
	<%= form_for(:project, url: submit_project_path, remote: true, html: {id: 'song-form'}) do |f| %>
	  <%= f.text_field :name, :placeholder => "New Project Name", required: true %>
	  <div id= "project-name-error" style="color:red;"></div>
	  </br>
	  <%= f.text_area :desc, :placeholder => "New Project Description" %>
	  </br>
	  <%= submit_tag "CREATE PROJECT", class: "btn btn-blue-green", data: { disable_with: "Creating..." } %>
	<% end %>
</div>

<div class="field offWhite">
	<%= form_for(:project_song, url: submit_song_project_path(@song), remote: true, html: {id: 'song-form'}) do |f| %>
	  <div class="styled-select">
	    <%= f.select(:project_id, options_for_select(user_project_lists), prompt: "Select a Project to Add Song") %>
	  </div>
	  <div id= "project-error" style="color:red;"></div>
	  </br>
	  <%= f.text_area :desc, :placeholder => "Add some personal notes about this song" %>
	  <div id= "desc-error" style="color:red;"></div>
	  </br>
	  <%= submit_tag "ADD SONG", class: "btn btn-blue-green", data: { disable_with: "Adding..." } %>
	<% end %>
</div>

<script>
 $(function(){

 	$('#new_project_popup').click(function(){
 		$('.new-project').toggle();
 		$('#project-success').html("");
 	});

 });
</script>

app/views/projects/edit.html.erb
<%= render partial: "projects/form", locals: {heading: "Edit Project", btn_text: "Update"} %>

app/views/projects/edit_song.html.erb
<%= content_for :id, 'share-quote-modal' %>

<h1>Edit This Song</h1>
<div class="field offWhite">
	<%= form_for(:project_song, url: submit_song_project_path(@song), remote: true, html: {id: 'song-form'}) do |f| %>
	  <%= f.select(:project_id, options_for_select(user_project_lists, selected: @project_song.try(:project_id)), prompt: "Select a Project") %>
	  <div id= "project-error" style="color:red;"></div>
	  </br>
	  <%= f.text_area :desc, :placeholder => "Add personal notes about the song" %>
	  <div id= "desc-error" style="color:red;"></div>
	  </br>
	  <%= submit_tag "Update Song", class: "btn btn-primary submitBtn", data: { disable_with: "Updating..." } %>
	<% end %>
</div>

app/views/projects/index.html.slim
- set_meta_tags  site:   'Zudo Music Licensing for Film, TV and Video Games', 
          title:  'MY PROJECTS', 
          reverse: true,
          description: "This is a personalized page containing private projects playlist information.",
          noindex: false,
          canonical:"http://www.zudomusic.com/placements",
          author:  "https://plus.google.com/u/1/117370898715446501614"
- set_meta_tags og: { title:  'MY PROJECTS | Zudo Music Licensing for Film, TV and Video Games',
          type:   'website',
          url:    'http://www.zudomusic.com/projects',
          image:  'http://zudomusic.com/zudo_music-01-wmd-min.png',
          description: "This is a personalized page containing private projects playlist information."}
- set_meta_tags twitter: { card:   "summary_large_image",
          site:   "@ZudoMusic",
          title:  "MY PROJECTS | Zudo Music Licensing for Film, TV and Video Games",
          image:  "http://zudomusic.com/zudo_music-01-wmd-min.png",
          description: "This is a personalized page containing private projects playlist information."}

.page-title
  .center.container
    h1 My Projects
    p= link_to 'Create New project', new_project_path, :class => 'btn btn-ghost'

table.songlist
  thead.songlistHead
    tr
      th Name
      th Description
      th

  tbody
    - for project in @projects
      tr.songRow
        td #{project.name}
        td #{project.desc}
        td.storeBTNs
          = link_to project_path(project) do
            i.ion-ios-eye-outline
          = link_to edit_project_path(project) do
            i.ion-ios-compose-outline
          = link_to project_path(project), method: :delete, data: {confirm: 'Are you sure?'} do
            i.ion-ios-trash-outline

    - if @projects.empty?
      tr.songRow
        td colspan="5"
          | There is no project exists.

app/views/projects/new.html.erb
<%= render partial: "projects/form", locals: {heading: "Add New Project", btn_text: "Create"} %>

app/views/projects/show.html.slim
- set_meta_tags  site: "Zudo Music Licensing for Film, TV and Video Games", 
          title:  "#{@project.name} Playlist", 
          reverse: true,
          description: "Welcome to #{@project.name} playlist.",
          noindex: false,
          canonical:"http://www.zudomusic.com/projects/#{@project.id}",
          author:  "https://plus.google.com/u/1/117370898715446501614"
- set_meta_tags og: { title:  "#{@project.name} Playlist | Zudo Music Licensing for Film, TV and Video Games",
          type:   'website',
          url:    "http://www.zudomusic.com/projects/#{@project.id}",
          image:  'http://zudomusic.com/zudo_music-01-wmd-min.png',
          description: "Welcome to #{@project.name} playlist."}
- set_meta_tags twitter: { card:   "summary_large_image",
          site:   "@ZudoMusic",
          title:  "#{@project.name} Playlist | Zudo Music Licensing for Film, TV and Video Games",
          image:  "http://zudomusic.com/zudo_music-01-wmd-min.png",
          description: "Welcome to #{@project.name} playlist."}
- provide(:keywords, "Music Library")

.page-title
  .center.container
    h1
      =@project.name
    p="Welcome to #{@project.name} playlist"

section.section#favorites-page
  table.songlist
    thead.songlistHead
      tr
        th 
        th Song
        th Artist
        th Personal  Notes
        th
    tbody
      - @songlist.each do |songlist|
        tr.songRow
          - song = songlist.song
          td= image_tag song.image.url, class: 'songRowArt'
          td= link_to song.title, song_path(song)
          td= link_to song.artist.name, artist_path(song.artist), class: 'songRowArtist'
          td= songlist.desc
          td.storeBTNs
            - if user_signed_in? && songlist.user_id == current_user.id
              = link_to edit_song_project_path(songlist), data: {modal: true} do
                i.ion-ios-compose-outline
              = link_to delete_song_project_path(songlist ), method: :delete, data: {confirm: 'Are you sure?'} do
                i.ion-ios-trash-outline
            = link_to share_song_path(song), data: {modal: true} do
              i.ion-ios-redo-outline
            - if user_signed_in?
              = link_to add_song_project_path(song), data: {modal: true} do
                i.ion-ios-plus-empty
            - else
              a data-must-be-logged-in=true href="#"
                i.ion-ios-plus-empty
            - if user_signed_in?
              - favorited = current_user.favorite_projects.exists?(id: song.id)
              span.favoriteProject data-status=(favorited ? 'unfavorite' : 'favorite')
                = link_to favorite_projects_path(id: song.id), method: :post, remote: true, class: 'favorite' do
                  i.ion-ios-heart-outline
                i.ion-ios-reload.loading
                = link_to favorite_project_path(id: song.id), method: :delete, remote: true, class: 'unfavorite' do
                  i.ion-ios-heart
              / = link_to download_song_path(song) do
                i.ion-ios-cloud-download-outline
              = link_to add_to_cart_song_path(song), data: {modal: true} do
                i.ion-ios-cart-outline
            - else
              a data-must-be-logged-in=true href="#"
                i.ion-ios-heart-outline
              / a data-must-be-logged-in=true href="#"
                i.ion-ios-cloud-download-outline
              a data-must-be-logged-in=true href="#"
                i.ion-ios-cart-outline


  

app/views/projects/submit_project.js.erb
$('#project-name-error').html("");
$('#project-success').html("");
<% if @errors.present? %>
  $('#project-name-error').html('<%= @errors %>');
<% else %>
  $('#project_name').val(null);
  $('.new-project').hide();
  $('#project_song_project_id').html('<%= j render("projects/project_list") %>');
  $('#project-success').html('<%= @success %>')
<% end %>

app/views/projects/submit_song.js.erb
$('#project-error').html("");
$('#desc-error').html("");
<% if @errors.present? %>
  <% if @errors[:project].present? %>
    $('#project-error').html('<%= @errors[:project] %>');
  <% elsif @errors[:desc].present? %>
    $('#desc-error').html('<%= @errors[:desc] %>');
  <% end %>
<% elsif @success.present? %>
   $('.close-reveal-modal').click();
   alert("<%= @success %>");
<% end %>