config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  resources :users
  resources :instruments, only: [:new, :edit, :create, :update, :destroy]
  resources :tempos, only: [:new, :edit, :create, :update, :destroy]
  resources :keys, only: [:new, :edit, :create, :update, :destroy]
  resources :eras, only: [:new, :edit, :create, :update, :destroy]
  resources :paces, only: [:new, :edit, :create, :update, :destroy]
  resources :moods, only: [:new, :edit, :create, :update, :destroy]
  resources :genres, only: [:new, :edit, :create, :update, :destroy]
  resources :artists
  resources :songs
  resources :projects
  get 'projects/add_song/:song_id' => 'projects#add_song', as: :add_song_project
  post 'projects/submit_song/:song_id' => 'projects#submit_song', as: :submit_song_project
  get 'edit_song_project/:id' => 'projects#edit_song', as: :edit_song_project
  delete 'projects/delete_song/:id' => 'projects#delete_song', as: :delete_song_project
  post 'projects/submit_project' => 'projects#submit_project', as: :submit_project
  resources :favorite_projects, only: [:create, :destroy, :playlist]
  resources :quotes do
    member do
      get :share
    end
  end
  resources :posts do
    resources :comments
  end
  resources :songs do
    member do
      get :download
      get :share
      get :add_to_cart
      post :add_to_cart
      post 'add_song'
      post 'remove_song'
      post :update_play_count
    end
  end
  resources :playlists do
    member do
      post 'add_song'
      post 'remove_song'
    end
  end
  resources :contacts, only: [:new, :create]

  resources :shopping_cart_items, only: [:destroy]
  
  get '/cart', to: 'shopping_cart_items#index'

  post '/checkout', to: 'shopping_cart_items#checkout'

  get '/purchases', to: 'purchase_items#index'
  get '/placements', to: 'purchase_items#placements'

  get '/purchased_items/:id/download', to: 'purchase_items#download', as: :download

  get '/home', to:  'pages#home'
  get '/credits', to: 'users#user_credits'
  get '/new_credit', to: 'users#new_credit'
  post '/submit_credit', to: 'users#submit_credit'

  get '/usermod', to:  'users#admin'

  get '/relationships', to:  'artists#relationships'
  post '/save_similar_artist/:id', to:  'artists#save_similar_artist', as: :save_similar_artist
  post '/artists/save_featured/:id', to: 'artists#save_featured'
  post '/artists/save_as_active/:id', to: 'artists#save_as_active'
  match "/submit_your_music" => "artists#new_artist_submission", as: :submit_your_music, via: [:get, :post]
  get '/about', to:  'pages#about'

  get '/contact', to: 'contacts#new'

  get '/film', to:  'pages#film'

  get '/horror', to:  'pages#horror'

  get '/games', to:  'pages#games'

  get '/ads', to:  'pages#ads'

  get '/video', to:  'pages#video'

  get '/blog', to:  'posts#index'

  get '/terms', to:  'pages#terms'

  get '/submit', to:  'artists#new_artist_submission'

  get '/faq', to:  'pages#faq'

  get '/play', to: 'songs#library'

  get '/favorites', to: 'songs#favorite'

  get '/dabooth', to: 'pages#admin'

  get '/teamzudosongadminpage', to: 'songs#admin'
  get '/teamzudosongapprovalpage', to: 'songs#approvals'
  post '/approve_deny_song/:id', to: 'songs#approve_deny', as: :approve_deny_song
  get '/denied-songs', to: 'songs#denied_songs', as: :denied_songs
  get '/deny_song/:id', to: 'songs#deny_song', as: :deny_song

  get '/sorry', to: 'pages#deny'

  get '/studio', to: 'songs#seller'

  get '/romance', to: 'pages#romance'



  as :user do
    get "/login" => "devise/sessions#new"
    get '/signup', to: 'registrations#new'
  end

  get '/share_zudo', to: 'site#share_zudo', as: :share_zudo

  get '/must_login', to: 'site#must_login', as: :must_login

  root 'pages#home'

  get '/genres', to: redirect('/play')
  get '/genres/:id', to: redirect('/play')
  get '/moods', to: redirect('/play')
  get '/moods/:id', to: redirect('/play')
  get '/paces', to: redirect('/play')
  get '/paces/:id', to: redirect('/play')
  get '/eras', to: redirect('/play')
  get '/eras/:id', to: redirect('/play')
  get '/keys', to: redirect('/play')
  get '/keys/:id', to: redirect('/play')
  get '/tempos', to: redirect('/play')
  get '/tempos/:id', to: redirect('/play')
  get '/instruments', to: redirect('/play')
  get '/instruments/:id', to: redirect('/play')

end

app/models/era.rb
class Era < ActiveRecord::Base
	default_scope { order(name: :asc) }
	has_many :songs
	
	validates :name, :desc, presence: true
end

app/controllers/eras_controller.rb
class ErasController < ApplicationController
  before_action :set_era, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource except: [:index, :create, :show]
  # GET /eras
  # GET /eras.json
#  def index
#    @eras = Era.all    
#  end

  # GET /eras/1
  # GET /eras/1.json
#  def show
#  end

  # GET /eras/new
  def new
  end

  # GET /eras/1/edit
  def edit
  end

  # POST /eras
  # POST /eras.json
  def create
    @era = Era.new(era_params)
    respond_to do |format|
      if @era.save
        format.html { redirect_to @era, notice: 'Era was successfully created.' }
        format.json { render :show, status: :created, location: @era }
      else
        format.html { render :new }
        format.json { render json: @era.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eras/1
  # PATCH/PUT /eras/1.json
  def update
    respond_to do |format|
      if @era.update(era_params)
        format.html { redirect_to @era, notice: 'Era was successfully updated.' }
        format.json { render :show, status: :ok, location: @era }
      else
        format.html { render :edit }
        format.json { render json: @era.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eras/1
  # DELETE /eras/1.json
  def destroy
    @era.destroy
    respond_to do |format|
      format.html { redirect_to eras_url, notice: 'Era was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_era
      @era = Era.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def era_params
      params.require(:era).permit(:name, :desc)
    end
end

app/helpers/eras_helper.rb
module ErasHelper
end

app/views/eras/_form.html.erb
<%= form_for(@era) do |f| %>
  <% if @era.errors.any? %>
      <% @era.errors.full_messages.each do |message| %>
        <%= js add_gritter(message, :image => :warning ) %>
      <% end %>
  <% end %>

  <div class="field offWhite">
    <!--<%= f.label :name %><br>-->
    <%= f.text_field :name, :placeholder => 'Enter Era Name' %>
    <!--<%= f.label :desc %><br>-->
    <%= f.text_area :desc, :placeholder => 'Enter Era Description' %>
    <%= f.submit 'Save Era', :class => 'submitBTN' %>
  </div>
<% end %>

app/views/eras/edit.html.erb
<% provide(:title, "EDIT ERA") %>
<div class="page-title">
	<div class="container">
		<h1>Edit Era</h1>
		<p>Please enter information for all sections of the form below to enter a new era into the library.</p>
	</div>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Show', @era %> |
		<%= link_to 'Back', eras_path %>
	</div>
</div>

app/views/eras/index.html.erb
<% provide(:title, 'ERAS') %>
<% provide(:description, "Filter Songs by Era Time Period Category") %>
<% provide(:keywords, "Songs by Era") %>
<div class="page-title">
  <div class="container">
    <h1>Eras</h1>
    <p>Filter our library by any of the time periods below</p>
  </div>
</div>
<section class="section sect-pad">
  <div class="container">
    <% @eras.each do |era| %>
      <%= link_to era_path(era) do %>
        <div class="optCard">
          <div class="optCard-image offWhite">
            <%= image_tag('era_image') %>
          </div>
          <div class="optCard-title center">
            <h2><%= era.name %></h2>
          </div>
          <div class="optCard-desc center">
            <%= era.desc %>
          </div>
          <div class="optCard-admin">
            <% if can? :manage, Era %>
              <%= link_to 'Show', era %> | 
              <%= link_to 'Edit', edit_era_path(era) %> | 
              <%= link_to 'Destroy', era, method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </div>
        </div>
      <% end %>
    <% end %>
    <% if can? :manage, Era %>
      <div class="center">
        <%= link_to 'Add New Era', new_era_path, :class => 'btn btn-ghost' %>
      </div>
    <% end %>
  </div>
</section>

app/views/eras/new.html.erb
<% provide(:title, "ADD ERA") %>
<div class="page-title">
	<div class="container">
		<h1>Add New Era</h1>
		<p>Please enter information for all sections of the form below to enter a new era into the library.</p>
	</div>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Back', eras_path %>
	</div>
</div>

app/views/eras/show.html.erb
<% provide(:title, @era.name) %>
<% provide(:description, @era.name + " Songs Available for Synch Licensing in Film and TV Soundtracks") %>
<% provide(:keywords, @era.name + " Songs") %>
<div class="page-title">
	<div class="container">
		<h1><%= @era.name %> Songs</h1>
    	<p><%= @era.desc %></p>
	</div>
</div>
<section class="catPlayerWrap">
	<table class="songlist">
	  <thead class="songlistHead">
	    <tr>
	      <th>Artwork</th>
	      <th>Title</th>
	      <th>Artist</th>
	      <th>Genre</th>
	      <th>Mood</th>
	      <th>Pace</th>
	      <th>Key</th>
	      <th>Tempo</th>
	      <th>Instrument</th>
	      <th> </th>
	    </tr>
	  </thead>
	  <tbody>
	    <% Song.where(era_id: @era.id).each do |song| %>
	      <tr class="songRow">
	        <td>
	          <div class="songRowPlay">
	            <a href="#">
	              <i class="ion-ios-play"></i>
	              <%= image_tag song.image.url, class: 'songRowArt' %>
	            </a>
	          </div>
	        </td>
	        <td><a href="#"><%= link_to song.title, song_path(song.id) %></a></td>
	        <td><%= link_to Artist.find(song.artist_id).name, artist_path(song.artist_id) %></td>
	        <td><%= link_to Genre.find(song.genre_id).name, genre_path(song.genre_id) %></td>
	        <td><%= link_to Mood.find(song.mood_id).name, mood_path(song.mood_id) %></td>
	        <td><%= link_to Pace.find(song.pace_id).name, pace_path(song.pace_id) %></td>
	        <td><%= link_to Key.find(song.key_id).name, key_path(song.key_id) %></td>
	        <td><%= link_to Tempo.find(song.tempo_id).name, tempo_path(song.tempo_id) %></td>
           <td><%= link_to Instrument.find(song.instrument_id).name, instrument_path(song.instrument_id) %></td>
	        <td class="storeBTNs">
	            <a href="#"><i class="ion-ios-star-outline"></i></a>
	            <a href="#"><i class="ion-ios-cloud-download-outline"></i></a> 
	            <a href="#"><i class="ion-ios-cart-outline"></i></a>
	        </td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
</section>